# Config for Dependabot updates. See Documentation here:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Update GitHub actions in workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    # Every weekday
    schedule:
      interval: "daily"
    labels:
      - "deps update"
    commit-message:
      include: scope
      prefix: chore

  # Enable version updates for NPM
  - package-ecosystem: "npm"
    directory: "frontend/"
    groups:
      definitely-typed:
        patterns:
          - "@types*"
        update-types:
          - "minor"
          - "patch"
      clerk:
        patterns:
          - "@clerk*"
      radix-ui:
        patterns:
          - "@radix-ui*"
    ignore:
      - dependency-name: "@types*"
        update-types: ["version-update:semver-major"]
    # Every weekday
    schedule:
      interval: "daily"
    labels:
      - "deps update"
    commit-message:
      include: scope
      prefix: chore

  # Enable version updates for Docker
  # We need to specify each Dockerfile in a separate entry because Dependabot doesn't
  # support wildcards or recursively checking subdirectories. Check this issue for updates:
  # https://github.com/dependabot/dependabot-core/issues/2178
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `backend/compose/local/django` directory
    directory: "backend/compose/local/django/"
    # Every weekday
    schedule:
      interval: "daily"
    labels:
      - "deps update"
    commit-message:
      include: scope
      prefix: chore
    # Ignore minor version updates (3.10 -> 3.11) but update patch versions
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"

  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `backend/compose/production/django` directory
    directory: "backend/compose/production/django/"
    # Every weekday
    schedule:
      interval: "daily"
    labels:
      - "deps update"
    commit-message:
      include: scope
      prefix: chore
    # Ignore minor version updates (3.10 -> 3.11) but update patch versions
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"

  - package-ecosystem: "docker"
    directory: "backend/compose/production/postgres/"
    schedule:
      interval: "daily"
    labels:
      - "deps update"
    commit-message:
      include: scope
      prefix: chore

  # Enable version updates for Python/Pip - Production
  - package-ecosystem: "pip"
    # Look for a `requirements.txt` in the `backend` directory
    # also `setup.cfg`, `runtime.txt` and `requirements/*.txt`
    directory: "backend/"
    # Every weekday
    schedule:
      interval: "daily"
    labels:
      - "deps update"
    commit-message:
      include: scope
      prefix: chore
