volumes:
  backend_local_postgres_data: {}
  backend_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: backend_local_django
    container_name: backend_local_django
    env_file:
      - ./.envs/.local/.postgres
      - ./.envs/.local/.django
    ports:
      - 8000:8000
    volumes:
      - .:/app:z
    depends_on:
      - postgres
      - mailpit
    command: "/start"

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: backend_production_postgres
    container_name: backend_local_postgres
    volumes:
      - backend_local_postgres_data:/var/lib/postgresql/data
      - backend_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  mailpit:
    image: axllent/mailpit:latest
    container_name: backend_local_mailpit
    ports:
      - "8025:8025"
