# Generated by Django 4.2.8 on 2023-12-12 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0002_user_public_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="users.user",
                    ),
                ),
                ("cover", models.ImageField(blank=True, upload_to="artists/covers/")),
                ("show_image", models.BooleanField(default=True)),
            ],
            bases=("users.user",),
        ),
    ]
