# Generated by Django 4.2.8 on 2023-12-14 01:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artists", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="artist",
            name="instagram_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="artist",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="artist",
            name="twitter_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
