# Generated by Django 4.2.8 on 2023-12-12 20:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("artists", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artist",
            name="show_image",
        ),
    ]
