# Generated by Django 4.2.11 on 2024-03-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_artist_first_name_artist_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='artist',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.URLField(blank=True, default='https://img.clerk.com/preview.png'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='instagram_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='artist',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='artist',
            name='twitter_link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
