# Generated by Django 4.2.13 on 2024-05-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_alter_music_artist'),
        ('artists', '0004_alter_artist_about_alter_artist_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='liked_musics',
            field=models.ManyToManyField(blank=True, related_name='liked_artists', to='musics.music'),
        ),
    ]
