#!/bin/bash

curl "$GCP_CREDENTIALS_URL" -o /app/$GOOGLE_APPLICATION_CREDENTIALS
python /app/manage.py collectstatic --noinput
exec /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app
