# Generated by Django 4.2.9 on 2024-01-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music_contexts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="musiccontext",
            name="music_state",
            field=models.CharField(
                choices=[("playing", "Playing"), ("paused", "Paused")], default="paused", max_length=10
            ),
        ),
    ]
