# Generated by Django 4.2.8 on 2023-12-28 15:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("musics", "0002_alter_music_artist"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="MusicOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField()),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("music", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="musics.music")),
            ],
            options={
                "verbose_name": "Music Order",
                "verbose_name_plural": "Music Orders",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="playlists")),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("object_id", models.UUIDField()),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
                ("musics", models.ManyToManyField(blank=True, through="playlists.MusicOrder", to="musics.music")),
            ],
        ),
        migrations.AddField(
            model_name="musicorder",
            name="playlist",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="playlists.playlist"),
        ),
    ]
