# Generated by Django 4.2.8 on 2023-12-28 15:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="musicorder",
            options={
                "ordering": ["order", "added_at"],
                "verbose_name": "Music Order",
                "verbose_name_plural": "Music Orders",
            },
        ),
    ]
