# Generated by Django 4.2.8 on 2023-12-28 15:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0003_alter_musicorder_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="musicorder",
            options={"ordering": ["order"], "verbose_name": "Music Order", "verbose_name_plural": "Music Orders"},
        ),
    ]
