# Generated by Django 4.2.11 on 2024-03-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0004_alter_musicorder_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
