# Generated by Django 4.2.8 on 2023-12-13 17:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("external_id", models.CharField(editable=False, max_length=32, unique=True)),
                ("username", models.CharField(max_length=64, unique=True)),
                ("email", models.EmailField(max_length=254)),
                ("image", models.URLField(blank=True, default="https://img.clerk.com/preview.png", null=True)),
                ("public_metadata", models.JSONField(blank=True, default=dict, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
