# Generated by Django 4.2.8 on 2023-12-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="public_metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
