# Generated by Django 4.2.8 on 2023-12-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_public_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.URLField(blank=True, default="https://img.clerk.com/preview.png"),
        ),
    ]
