# Generated by Django 4.2.13 on 2024-05-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_alter_music_artist'),
        ('users', '0003_alter_user_first_name_alter_user_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_musics',
            field=models.ManyToManyField(blank=True, to='musics.music'),
        ),
    ]
