# Generated by Django 4.2.13 on 2024-05-31 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_alter_music_artist'),
        ('users', '0004_user_liked_musics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='liked_musics',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='musics.music'),
        ),
    ]
