# Generated by Django 4.2 on 2023-04-28 20:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('identifier', models.CharField(editable=False, max_length=32, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=64, unique=True)),
                ('image', models.URLField()),
            ],
        ),
    ]
