name: Deploy Backend

on:
  push:
    branches: ["master", "main"]
    paths-ignore: ["!backend"]

concurrency:
  group: ${{ github.run_id }}
  cancel-in-progress: true

jobs:
  linter:
    name: Pre-Commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: python -m pip install pre-commit
      - run: python -m pip freeze --local
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-3|${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Running pre-commit
        working-directory: "backend"
        run: pre-commit run --show-diff-on-failure --color=always --all-files

  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    needs: linter

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Railway
        run: bash <(curl -fsSL cli.new) -y

      - name: Deploy
        run: railway up -d -s ${{secrets.RAILWAY_SERVICE}}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
