name: Frontend - CI|CD

on:
  pull_request:
    paths: ["frontend/**"]
  push:
    branches: ["master", "main"]
    paths: ["frontend/**"]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  SKIP_ENV_VALIDATION: true

jobs:
  linter:
    name: Lint Styles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version: "18"
          cache-dependency-path: ./frontend/pnpm-lock.yaml

      - name: Install dependencies
        working-directory: frontend
        run: pnpm install

      - name: Running lint
        working-directory: frontend
        run: pnpm lint

  deploy-frontend:
    if: github.event_name == 'push'
    name: Deploy Frontend
    runs-on: ubuntu-latest
    needs: linter

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Railway
        run: bash <(curl -fsSL cli.new) -y

      - name: Deploy
        run: railway up -d -s ${{secrets.RAILWAY_FRONT_SERVICE}}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
