name: Frontend - CI|CD

on:
  pull_request:
    paths: ["frontend/**"]
  push:
    branches: ["master", "main"]
    paths: ["frontend/**"]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  SKIP_ENV_VALIDATION: true

jobs:
  linter:
    name: Lint Styles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          package_json_file: ./frontend/package.json

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version-file: .nvmrc
          cache-dependency-path: ./frontend/pnpm-lock.yaml

      - name: Install dependencies
        working-directory: frontend
        run: pnpm install

      - name: Running lint
        working-directory: frontend
        run: pnpm lint
