# Generated by Django 4.1.5 on 2023-01-22 18:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('d6c4f5cf-5561-4d84-849e-1d4804725067'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('481d1443-1118-4b20-9181-098b59e9314f'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=80)),
                ('cover', models.ImageField(upload_to='cover')),
                ('audio', models.FileField(upload_to='audio')),
                ('singers', models.ManyToManyField(related_name='singers', to='music.singer')),
            ],
        ),
    ]
