# Generated by Django 4.1.5 on 2023-02-03 00:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='artists')),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=80)),
                ('cover', models.ImageField(upload_to='cover')),
                ('audio', models.FileField(upload_to='audio')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.artist')),
                ('participants', models.ManyToManyField(blank=True, related_name='participants', to='music.artist')),
            ],
        ),
    ]
