# Generated by Django 4.1.5 on 2023-01-28 21:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('image', models.ImageField(upload_to='singers')),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=80)),
                ('cover', models.ImageField(upload_to='cover')),
                ('audio', models.FileField(upload_to='audio')),
                ('singers', models.ManyToManyField(related_name='singers', to='music.singer')),
            ],
        ),
    ]
