# Generated by Django 4.1.5 on 2023-01-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='image',
            field=models.ImageField(blank=True, upload_to='singers'),
        ),
    ]
