# Generated by Django 4.1.5 on 2023-02-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='letters',
            field=models.TextField(blank=True),
        ),
    ]
